### ISSUE TITLE
How to only validate on submit?

### ISSUE THREAD

**Issue by cmwelsh** [christianalfoni/formsy-react#1]
Hi, I really appreciated your blog post and this accompanying library. It works very well for me. However, I have one issue that seems really simple. I hesitate to ask because I must be overlooking something but here it is:

How to only validate on submit? Right now it shows an error when the user types the first letter of their email address (not a valid email address), and then it shows an error when they type the first letter of their password (password is not enough characters).

Ideally, it would only show these errors when the field "blurs" (this would be great), or perhaps other people might want to validate on submit (this would be ok).

**Comment by gilbarbara** [comment]
hey Christian! 

I'm having a similar problem. I've made a global Input component that sometimes I need to set the value  but other times I won't.

```
<input
type={this.props.type}  
name={this.props.name}  
value={this.getValue()}  
/>
```

Since I want to validate fields using `onBlur` the value won't be set until I call `this.setValue()` which in turn would trigger the validation.
Is there any way to `setValue` without triggering the validations?

Cheers!
