### ISSUE TITLE
Input is pristine?

### ISSUE THREAD

**Issue by FoxxMD** [christianalfoni/formsy-react#10]
Is there anyway, within formsy-react, to tell if an input has not been touched yet? On resetForm I would like to be able to reset all the of the validation errors for inputs so they don't show "this is required" after clearing a form.

I've rolled my own for first interaction with an input using a state variable on my input component that gets changed to "dirty" when the input triggers onBlur -- the variable is then part of conditional logic to determine when to show an error (aka only have the input has been touched by user input) but this doesn't help if I use resetForm.

**Comment by christianalfoni** [comment]
Hi @FoxxMD , this is a very good point!

We could add a new method to the form elements, something like: "isPristine()"? So you could check:

```javascript
if (this.isRequired() && this.isPristine()) {
  // Show required
}
```

Could that work?

**Comment by FoxxMD** [comment]
That would be perfect.

Behaviors to consider for `isPristine()`:

**What will trigger the change?** 

I'm using `onBlur` but there might be benefits to letting the user decide (someone else may want to trigger on `onChange`

**Could all inputs be triggered globally?**

I'm thinking of a use case where a user only touches some inputs and ignores other, then tries to submit a form.

* User triggers `onSubmit`
* `isPristine` is set to false for all inputs even if they have not been touched so that validation displays for the entire form. (Something to consider if `resetForm` is going to do the opposite IE set `isPristine` to true for all inputs)

**Programatic triggering?**

The only use case I can think of is if you have two related inputs and you want one to have validation triggered after the first one is touched as a visual cue to the user.

***

In any case, only the first two are relevant to my scenario :) If you'd like any help implementing this let me know!

**Comment by christianalfoni** [comment]
Hi again,

**What triggers the change?**
Good point! :-) Conceptually you want to tell the parent form when the input is "touched", whatever that might be. By default that would be when the input changes its value, which lets us hook up "isPrestine" to the "setValue" method. But as you say, you might do it when blurring. To keep things simple I would suggest that you would have to run "this.setValue(this.getValue())" when blurring to achieve the prestine effect. That will keep the API simple, as it is only the "setValue" method that changes the pristine value. I fear the API becomes very complex if you get too much control of this. What do you think? 

**Could all inputs be triggered globally?**
Another good point! :-) I agree that submitting the form should set all elements to `ìsPrestine() -> false`, as kind of a "global touch". At least make that part of the first implementation. It can be reconsidered if there is feedback on scenarios where that might be a problem. This happens in the background so can easily change it.

**Programatic triggering?**
Hm, yeah, it is an interesting scenario. Though I think it will add too much complexity, at least for now. I think it is a good idea to get some more experience with "prestining" in Formsy :-)

Let me know what you think and we can start the implementation. I think it is time to bring in some tests now too, so that should also be part of the next release. Feel free to contribute to this with pull requests, or I will start on this next Wednesday :-)

**Comment by FoxxMD** [comment]
> What triggers the change? 

Your approach makes more sense. Keeping `isPristine` hooked into `setValue` definitely makes usage simpler and still allows for customizing the cue (like you mentioned in my case for `onBlur`).

>programatic triggering

Also agree with you that it's too complex to try to implement now. It'd be better to wait and see how the api gets used first.

I will put in a pull request or two before wednesday hopefully!

**Comment by christianalfoni** [comment]
Hi again @FoxxMD!

I have the day off tomorrow so I will be looking into all current issues and create tests, but do feel free to apply a pull request, it would be cool to see how you would solve it in the current codebase :-)

About your question I do see your point, but I think it should be up to the developer to decide if the form could be submitted or not while invalid. For example by disabling the submit button when the form is invalid. That is why the "onInvalid" and "onValid" handlers where introduced. Give more flexibility :-) Does that make sense? Please let me know if there are scenarios I have not considered.

**Comment by christianalfoni** [comment]
Okay, this is now in the code, also with a test. Will be part of todays release.
