### ISSUE TITLE
No way to POST form to server

### ISSUE THREAD

**Issue by vinylrain** [christianalfoni/formsy-react#152]
It amazes me that there is no built in way to submit the form to the server. I don't want to do $.post. I want an action with a URL and a POST method. I've tried setting those attributes in <Formsy.Form> and programmatically to no avail. None of the examples even show what happens after you click submit. Nobody alerts with a JSON string after submitting a form! Any way to submit a form normally so I can use my server side validation and routing?

**Comment by Semigradsky** [comment]
You can use your favorite library for this. For example:
```js
var request = require('superagent');
...
var Login = React.createClass({
  ...
  submit: function (data) {
    request.post('/app/login').end(function(err, res){
      // do smth
    });
  },
  ...
  render: function () {
    return (
      <Formsy.Form onInvalidSubmit={this.submit}>
        ...
```

**Comment by vinylrain** [comment]
I don't want to do client-side requests. I want to use HTTP POST. Method="post" action="mypage.php"

Thanks for setting the label. I couldn't do it on my phone.

**Comment by Semigradsky** [comment]
I'm sorry, I can't quite understand why not make http post requests from the script.

**Comment by vinylrain** [comment]
Because then I have to handle errors and routing clientside. That would make a huge mess in my code.

**Comment by vinylrain** [comment]
I believe that this feature does not exist, so this is less of a question and more of a request.

**Comment by ericdfields** [comment]
I can't quite tell what you're going for either. Do you want to perform client-side validation and then, if the validations are all good, perform a standard POST?

**Comment by vinylrain** [comment]
Yes.

**Comment by ericdfields** [comment]
You could use a number of the [validation-related methods](https://github.com/christianalfoni/formsy-react/blob/master/API.md#validationerrors) described in the API. 

[The example in the Readme](https://github.com/christianalfoni/formsy-react#formsy-gives-you-a-form-straight-out-of-the-box) will, for example, disable the submit button until the form is valid. Upon submitting the form, it will do a standard POST.

**Comment by vinylrain** [comment]
It does not do a standard POST. It triggers a submit method that has some unknown function. There is also no way to set an action or a method AFAIK.

**Comment by ericdfields** [comment]
My apologies. You’re correct and it does expect you to handle POST your own way. Here is the function: https://github.com/christianalfoni/formsy-react/blob/master/src/main.js#L81-L94 <https://github.com/christianalfoni/formsy-react/blob/master/src/main.js#L81-L94>

I don’t think you can pull of what you want to then. Just might not be the library you’re looking for.

**Comment by vinylrain** [comment]
Yeah, this is more of a feature request than a question now.

**Comment by Checksum** [comment]
+1 to this. I'm using formsy mainly to maintain state for a complex form, including custom validations. Works well for that. What I would then like to do is trigger a normal HTTP post by passing the action and method parameter.

If this is something that will be considered, I can send a pull request.

**Comment by christianalfoni** [comment]
Hi there,

Formsy is built for flexibility. There are so many different ways of handling a form and to support most of them Formsy has a lot of hooks. Initially Formsy did support posting data directly to the server and handle any errors, but the implementation was too specific. There were so many requests on support of headers, map errors from server etc. It just got way out of control. So instead of having one very opinionated implementation of talking to the server, it has an extremely flexible hook that lets you do it exactly as you want to.

So I am sorry to say that this will not be implemented... and I can not really see that this is a problem:

```js
sendData(form, reset, invalidate) {
  myAjaxLib.post('/form', form)
    .success(doWhatever)
    .error(invalidate);
},
render() {
  return <Formsy.Form onSubmit={this.sendData}/>
}
```

**Comment by Nopik** [comment]
I also can't believe that Formsy doesn't have this out of the box. Thats literally a book example of what `<form>` is for. And explaination that it does so, because of flexibility is really astounding.. as Formsy out of the box is not flexible enough to support using the existing mechanisms (and e.g. getting html response from submit, or handle `target` property of `<form>`).

Anyway, I added https://github.com/christianalfoni/formsy-react/pull/441 to add support for standard submit.
