### ISSUE TITLE
Custom submit button

### ISSUE THREAD

**Issue by mschipperheyn** [christianalfoni/formsy-react#2]
Is it possible to have more flexibility for your own submitButton HTML. We for instance sometimes use icons for submitbuttons. The idea of Formsy taking over the rendering of this aspect seems a bit heavy handed. Formsy can catch the form submit event without this.

**Comment by christianalfoni** [comment]
Hi again @mschipperheyn , this is what I suggest:

Since the lib is pretty new I would like to do an API change. First remove anything related to default buttons:

```javascript
Formsy.defaults({
  contentType: 'urlencoded', // default: 'json'
  hideSubmit: true, // REMOVE IT
  submitButtonClass: 'btn btn-success', // REMOVE IT
  cancelButtonClass: 'btn btn-default', // REMOVE IT
  buttonWrapperClass: 'my-wrapper' // REMOVE IT
});
```

Instead add two new handlers for the form:

```javascript
<Formsy.Form onInvalid={this.disableButtons} onValid={this.enableButtons}></Formsy.Form>
```

That way you get a lot more flexibility. Yes, you would have to code that default behavior yourself, but the API is simpler and more flexible.

What do you think?

**Comment by mschipperheyn** [comment]
Yeah, providing handlers would make a lot more sense.

**Comment by christianalfoni** [comment]
Got those handlers in place :-)

**Comment by srconklin** [comment]
I followed the advice above and changed the onChange to onBlur for a login form. (data validation while typing email and password for a login modal is annoying)... that worked great! 

I also used the form in the sample here 
https://github.com/christianalfoni/formsy-react#formsy-gives-you-a-form-straight-out-of-the-box

so that the button is disabled until data validation is complete. 
that i also working great! 

Then I modified MyInput component to place the name and id the input into the input tag itself like so:
 <input id={this.props.name} name={this.props.name} type={this.props.type} onBlur={this.changeValue}  onChange={this.handleChange} className="form-control" value={this.state.theValue} placeholder={this.props.placeHolder} />

which makes google Chrome recognize it as a common form element and autofill it...
which i find very useful... 
(until i gave the input tag the email and password names, there was no autofilling)

But then I noticed that when the form loads the onInvalid={this.disableButton}  handler 
 fires which sets the canSubmit = false and overrides my default setting of canSubmit = true

Now , i am left with a form that has good cached input but i cannot submit it until i blur one of the fields.

so....
Why does the onInvalid handler fire on load?  
or more importantly do you know of a work-around to make it where the button is NOT disabled until the user actually types something in and blurs out of the field? 
OR how can enable the button on load? 

http://www.evernote.com/shard/s349/sh/f5c5714e-583a-4c76-858e-633b86fceb24/c9958eed29fdf12bfdda0160c57da9d8

**Comment by srconklin** [comment]
arghh! I posted this to the wrong issue.. sorry.. 
when i said.. "follow the advice above" I was refering to what you recommended to the user in this thread
https://github.com/christianalfoni/formsy-react/issues/1

**Comment by srconklin** [comment]
Now i see that my code that i was referring to  was removed by github
this is what i was referring to  when i said how i modified the MYInput component like so

id={this.props.name} name={this.props.name} 

I added these properties to input tag.

**Comment by srconklin** [comment]
Sorry to bother.. but i turned off disableButton just to test something and realized that when the input boxes are prefilled with the autofill data from chrome.. the this.setValue function is never called....
 // setValue() will set the value of the component, which in
  // turn will validate it and the rest of the form
  changeValue: function(event) {
    this.setValue(event.currentTarget.value);
  },

What would be the best practice for calling this function to set the value of the component when the component mounts?

**Comment by srconklin** [comment]
Sorry to Bother... Disregard all my comments. i have figured out what i need and some of the issues that i reported were because of my own mistakes.

**Comment by christianalfoni** [comment]
Hehe, no worries @srconklin :-)

If you have time to summarize where the mistakes were made, I could update the readme and make some things more clear. To prevent others meeting those same challenges. 

If you have time and see any value in it of course :-)

**Comment by asafshen** [comment]
Hey @christianalfoni @srconklin 
I ran into this issue as well (Chrome autofill values do not trigger input `onChange`)

Solved it by this by the following:
```
componentDidMount() {
    setTimeout(() =>{
      const input = this.refs[this.props.name];
      const autofillValue = input.defaultValue;
      if(autofillValue) {
        this.props.setValue(this.state.value);
      }
    },2000);
  }

render () {
  return (
   <div>
       ....
       <input 
         ... 
         ref={this.props.name}

      />
   </div>
  );
```

* the timeout got by trial and error...
