### ISSUE TITLE
How to show error message on submit?

### ISSUE THREAD

**Issue by salayev** [christianalfoni/formsy-react#216]
If I set `required` property on the input component then `showError()` and `getErrorMessage()` don't work properly if the input value is empty and user presses submit. `showError` is `false` and `getErrorMessage()` returns `null`.

If I don't set `required` property it works as expected but then `isRequired()` returns `false` which is not true because the field must be valid to pass.

Am I not understanding your implementation of `required`?

**Comment by christianalfoni** [comment]
Hi @salayev ,

Validation vs required is a surprisingly difficult concept. `validations` is related to `showError` and `getErrorMessages`. `required` is related to `showRequired()`. So you never check errors related to required. The reason is that they are two different things. You want to indicate a required input differently than when a validation is wrong :-)

**Comment by salayev** [comment]
Thanks for the explanation, why `required` though, in HTML5 spec it is the validations, may  be different name :)?
