### ISSUE TITLE
Question: Rendering a Formsy.Mixin component outside of a Formsy.Form

### ISSUE THREAD

**Issue by eriklharper** [christianalfoni/formsy-react#256]
I am porting tests over from formsy 0.14 to the latest 0.17 and noticed that some tests are breaking where I'm rendering a `FormsyTextInput` right into the document directly:

```
var component = TestUtils.renderIntoDocument(
      <FormsyTextInput
        name="TestTextInput"
        displayErrors={false}
        required />
    );
```

In 0.17 its throwing this error:

```
Uncaught TypeError: Cannot read property 'attachToForm' of undefined  Mixin.js:62
```

I just want to know if the 0.17 API of Formsy expects all components using Formsy.Mixin to be wrapped inside of a Formsy.Form in order for them to work, or if this is a potential issue with the 0.17 release.

Thanks! and appreciate the quality work you're putting into this project :+1:

**Comment by dimlock** [comment]
Also having this `<Formsy.Form>` dependency problem but for different use cases:

I have a custom checkbox which could be used in a form as normal or in a non-form context such as a control to select a row in a data grid. I would either have to create and use two checkbox components throughout my app (a base checkbox and a Formsy friendly one that extends it) which isn't good, or wrap all checkboxes in a `<Formsy.Form>` which is over-kill in the case.

The same thing could happen for custom radio buttons used purely for list selection or a <select> used purely for navigation.

Not sure how hard the dependency is, but the ideal would be to have checks for lack of context (surrounding Formsy.Form) and do nothing rather than error thus allowing single Formsy friendly custom control that will work with or without a surrounding Form.

:grinning:

**Comment by clayne11** [comment]
A much better solution to this is to separate out the Formsy dependency into a higher-order-component rather than a mixin.

When you need to use a component within a Formsy.Form, wrap the component with the higher-order-component and use it in the form. When using it otherwise, use the plain component.

This is also a great solution for testing where you can test the component outside of the Formsy context.
