### ISSUE TITLE
using getModel on an ES6 class

### ISSUE THREAD

**Issue by maticrivo** [christianalfoni/formsy-react#293]
i have an es6 class that has a Formsy.Form and i want to manually getModel(). is that possible?
my class is something like this:
```
export default class MyForm extends React.Component {
  manuallyGetModel () {
    console.log(this.refs.form.getModel())
  }
  render () {
    return (
      <Formsy.Form ref='form' ...>
        ....
        <button onClick={this.manuallyGetModel.bind(this)}>get model</button>
      </Formsy.Form>
    )
  }
}
```

when i press the button to manually get the model i get a
`Uncaught TypeError: this.refs.form.getModel is not a function`

any idea how can i achieve that?

**Comment by Semigradsky** [comment]
Yeah, new Formsy version not realised yet.
@christianalfoni ping

**Comment by JeremyBYU** [comment]
I also need the getModel function. It doesnt seem to be available in the 0.17.0 release.  I see it on the master branch however.  

I'm having an issue where my package manager (Meteor) doesnt seem to work when referencing a specific git commit (in order to get master branch).  Would really like it if you could push this functionality into another version (like 0.18.0)

**Comment by abejfehr** [comment]
This ^^ it's a potential deal-breaker

**Comment by daGrevis** [comment]
Hello?!

**Comment by utkuturunc** [comment]
+1

**Comment by 0xori** [comment]
try this.refs.form.model , works for me.

**Comment by mantagen** [comment]
Thank you @0xori !!

Update API to reflect this?

**Comment by Semigradsky** [comment]
Sorry for the long pause. Formsy-react updated, check new version.
