### ISSUE TITLE
Add isFormChanged method

### ISSUE THREAD

**Issue by sdemjanenko** [christianalfoni/formsy-react#40]
I would like to be able to enable/disable save/reset buttons depending on if there are changes or not.  I image this would tie in to the most recent pristine value for each input.

**Comment by christianalfoni** [comment]
Hi @sdemjanenko,

You should be able to do that using the "onChange" property of the form? Or does that not suffice?

**Comment by sdemjanenko** [comment]
I don't think it quite works.  I've found that onChange does not fire for the initial render.  This makes it hard to get the initial state of the form.  I will be doing this on most of my forms.

I think storing the initial state and diff it with the current state is something Formsy could be quite excellent at.

**Comment by christianalfoni** [comment]
Yeah, you make a good point here, I will bring it in with the next version :-)

**Comment by christianalfoni** [comment]
hi again @sdemjanenko ,

Looking at this again I just want to discuss a bit more before implementing. I just have to make sure that I do not add something that does not cover the challenge you are having.

So, the issue here is that you want to grab the initial state of the form. Saying that you are referring to the inputs and their values? The object that you receive on `onChange`?

Would it not be possible to just set that initial state on your wrapping form component?

```js
var FormWrapper = React.createClass({
  getInitialState: function () {
    return {
      values: {
        foo: 'bar'
      }
    };
  },
  setValues: function (values) {
    this.setState({values: values});
  },
  render: function () {
    return (
      <Formsy.Form onChange={this.setValues}>
        <MyInput value={this.state.values.foo}/>
      </Formsy.Form>
    );
  }
});
```
And when the "onChange" event is received you use that to set the new values?

**Comment by christianalfoni** [comment]
Looking at the implementation it seems that you want to check if the values of the form has changed? So if a user has changed something back to the pristine value you want it to be "hasChanged = false"?

**Comment by eventhough** [comment]
@christianalfoni Is it possible to also add the ability to get only the changed input values when a form is submitted? If the input is still pristine, do not include the data in the submit function. This is useful for a database update where you really only need the values that have changed.

**Comment by christianalfoni** [comment]
@eventhough This is an interesting suggestion! Would you mind creating a new issue on that? I will close this now. I would suspect we have to add a flag-property to the form. Thanks :-)
