### ISSUE TITLE
this.refs.form.getModel() undefined inside form?

### ISSUE THREAD

**Issue by acomito** [christianalfoni/formsy-react#400]
I'm trying to use `this.refs.form.getModel()` to hide or show form fields based on another form fields current value, however `this.refs.form.getModel()` seems like it isn't available inside the form in the render function.

Is there a best practice for hiding/showing form fields based on another fields current value?

**Comment by prasanna1211** [comment]
One of the reason this.refs.form.getModel() is being is used for the same purpose. I guess in initial render refs is undefined since the component is yet to load. See whether if is that the case. 
One practice can be, have a common parent on top of both the forms. Provide callbacks to both the form. Maintain dependant form fields in state and access them appropriately.

**Comment by aesopwolf** [comment]
@acomito You're correct, you can't access `this.refs` inside the render function.

Hiding/showing form fields based on another fields current value really varies depending on your situation. Would you mind pasting some code? If not, then I would suggest using setting up an `onChange` handler for your `<Formsy.Form>`, for example:

```jsx
formChangeHandler(model) {
  if(model.employmentStatus === 'Full time') {
    this.setState({askForEmployerName: true});
  } else {
    this.setState({askForEmployerName: false});
  }
}
```

Then you can hide/show the "Employer Name" input in your form based on `this.state.askForEmployerName`.

I'm going to close this as is since it's not actual issue with formsy, but we can still continue the discussion.
