### ISSUE TITLE
Character-based filters don't honor international characters

### ISSUE THREAD

**Issue by amireldor** [christianalfoni/formsy-react#407]
When trying the _Dynamic Form Fields_ example, I entered some Hebrew characters on a field with the 'isAlphanumeric' filter but it did not validate. English characters were fine, but as soon as I added a Hebrew character the validation failed. The regex on the filter only checks for English letters and thus the validation fails. I believe this also fails on other international charachters, Thai, Chinese, Arabic, etc...

This is a bit tricky as JavaScript regexs are not UTF-8 friendly. There is a library called [XRegExp](http://xregexp.com/plugins/) which handles UTF-8 regexs but you don't want to add a library on top of your own library because that's funny. However, maybe you can "borrow" some code for detecting the international characters. I'm not sure, never dug into it too much, and it sounds funny as well.

In case anyone needs some Hebrew characters to copy paste and test: בהצלחה לכולם ויום הולדת שמח.

**Comment by aesopwolf** [comment]
This is a really good point, thanks for bringing it up. I've struggled with something similar when I wanted to allow emoji characters.

I think this can probably be solved in user land. We [expose a validator](https://github.com/christianalfoni/formsy-react/blob/master/API.md#validators) called `matchRegexp`. And since the [xregexp](https://www.npmjs.com/package/xregexp) library on npm advertises that it compiles to native RegExp objects then in theory you can just pass pass the compiled regular expression to `matchRegexp`.

Let me know if that works for you or not.

**Comment by amireldor** [comment]
It sounds as if it would work but I can't test that in a timely manner and get back here to report the results. If I do manage to get a project using formsy I will definitely try and let you know.

**Comment by aesopwolf** [comment]
I just gave it a quick test and it worked as expected! Didn't have to do anything special. For example:

```jsx
<InputGroup
  name="emoji"
  label="emoji"
  type="text"
  validations={{
    matchRegexp: XRegExp('^\\pS$', 'A'), // https://github.com/slevithan/xregexp#unicode
  }}
  validationError="Please enter an emoji"
/>
```

I'll leave this open for now and close it once I add a note to our documentation.

**Comment by amireldor** [comment]
Good to know it worked, thanks.

**Comment by aesopwolf** [comment]
Docs updated https://github.com/christianalfoni/formsy-react/blob/master/API.md#validators
