### ISSUE TITLE
Work with normal input/textarea/select components

### ISSUE THREAD

**Issue by sdemjanenko** [christianalfoni/formsy-react#43]
It would be awesome if I could drop in `<input type='text' name='foo' value='bar' />` and have it work with Formsy.

**Comment by christianalfoni** [comment]
Yeah, that would be awesome :-) I was thinking of including "clean implementations" of the default form elements. So instead of `<input type="text" name="foo" value="bar"/>` you would say: `<Formsy.Input type="text" name="foo" value="bar"/>` and you would get the exact same thing.

What do you think? Not possible to do it with native inputs, at least not with current implementation, and what current implementation details would be lost if going down that path.

It is an interesting idea for a second version of Formsy though. The lib is not really very "simplistic" right now, but it solves the complexity of forms I think, and that was the main focus of the first version :-)

**Comment by sdemjanenko** [comment]
I think `Formsy.Input` would be acceptable for the time being.  Down the road I could see some post-processing of the v-dom to wire up the standard inputs.

**Comment by christianalfoni** [comment]
Will include this on release after next one :-)

**Comment by eriklharper** [comment]
+1 for clean implementations of native dom inputs.  I think it would be good to package these up into the repo and provide some good usage docs and examples for newbies to get started easier.  I'm also seeing a benefit to have a place where the community can contribute their own Formsy Inputs.  Would be really cool to see other's approaches to solving their specific form problems and a great way to share the knowledge base across the React community.

**Comment by alexduan** [comment]
+1 - would definitely love to incorporate this with something like react-bootstrap

**Comment by christianalfoni** [comment]
@eriklharper Since you mentioned contributing, this would also be an awesome contribution. You seem to have some ideas there too ;-)

@alexduan Yeah, could have a separate project bringing wrapped bootstrap components. That would indeed be very nice :-)

**Comment by afitiskin** [comment]
What if instead of `Formsy.Input` implement something like `Formsy.InputContainer`, that will wrap any kind of input fields (native `<input>` or `<textarea>` or something like `react-select` or `react-slider`)? So we will be able use any kind of input without some workaround:
```
<Formsy.Form>
    <Formsy.InputContainer>
        <input type="email" ... />
    </Formsy.InputContainer>
    <Formsy.InputContainer>
        <ReactSelect ... />
    </Formsy.InputContainer>
</Formsy.Form>
```

It will be like a connector between the real input field and our form element, which will do all dirty job.

**Comment by christianalfoni** [comment]
hi @afitiskin and thanks for the suggestion!

Though I like the concept of a container, I am a bit uncertain how this would be reusable. I think it would be nice to just:

```js
<Formsy.Form>
    <Formsy.Input/>
    <Formsy.Textarea/>
</Formsy.Form>
```
And implement a Formsy version of displaying validation errors etc. ReactSelect would not work of course, but again you would have to implement all the required, validation error display etc., so you would have to build a form element component for ReactSelect regardless.

Let me know if I misunderstood your example!

**Comment by christianalfoni** [comment]
I have been thinking about this some more and though I think it is nice with a default set of elements I do not think Formsy itself should have this. There are just so many ways to handle validation. Its better that other projects provide form elements with custom validation handling in regards of UI.

Like the https://github.com/twisty/formsy-react-components project.

I will update the README to point to that project.
