### ISSUE TITLE
Property mutation warnings after updating to react 0.13.1 and Formsy 0.8.1

### ISSUE THREAD

**Issue by jmartin84** [christianalfoni/formsy-react#65]
Seeing the following warnings when using the dev version of react(0.13.1) and the Formsy.Mixin(8.1) on a custom element. Poked around some but wasn't able to figure out a way to fix the warnings without converting the affected props to state values.

Warning: Don't set .props._attachToForm of the React component. Instead, specify the correct value when initially creating the element. The element was created by Login.
Warning: Don't set .props._detachFromForm of the React component. Instead, specify the correct value when initially creating the element. The element was created by Login.
Warning: Don't set .props._validate of the React component. Instead, specify the correct value when initially creating the element. The element was created by Login.
Warning: Don't set .props._isFormDisabled of the React component. Instead, specify the correct value when initially creating the element. The element was created by Login.

**Comment by darth10** [comment]
This is from the `registerInputs` function, which mutates `props` of all child form input controls. Hmm...

**Comment by christianalfoni** [comment]
Hi guys,

Yeah. Formsy does take an approach with React that is not best practice. There is a new release coming up now with some more functionality. After that I will start on Formsy 2, which conforms more to best practices, but will probably have a few breaking changes.

The challenge is that a form needs to create a relationship with its children form elements. Now this is done by iterating the children of the form instance, adding some properties and a mixin on the form elements uses these props to communicate with the form instance.

An other way to go about this is using pure events, but that changes the syntax and I am unsure if it is doable. It would be something like this:

```js
var Form = React.createClass({
  mixins: [Formsy.FormMixin],
  render: function () {
    return (
      <Formsy.Form>
        <MyFormElement name="foo"/>
      </Formsy.Form>
    );
  }
});
```
The mixin finds the FormsyForm element in the component and registers custom event listeners like: "Formsy.setValue", which then the children form elements can trigger and will be catched by the parent form. The problem is that React JS does not support custom events, would have to use native events, which reduces the testability with Formsy as tests would have to be run in the browser. I think this might be a good tradeoff though. 

Let me create an issue discussing next version of Formsy :-)

**Comment by christianalfoni** [comment]
Linking to issue: #66
