### ISSUE TITLE
Is Formsy.Form::setInputValidationErrors() redundant?

### ISSUE THREAD

**Issue by marnusw** [christianalfoni/formsy-react#72]
It would seem `setInputValidationErrors()` and `updateInputsWithError()` does virtually the same thing. Am I missing something or could the single call to the former be replaced by the latter? 

The former method loops through all inputs and checks for associated errors while the latter loops through the provided errors and updates the related inputs which seems to be the better choice.

**Comment by marnusw** [comment]
It seems like `getCurrentValues()` could also be used instead of `updateModel()` and then the concept of `this.model` could be removed entirely. The only place where the model is actually used is in `submit()`, and then it is always regenerated from the input values anyway, so dropping the `model` property wouldn't make a difference as far as I can see?

If it seems to you that I'm correct and you're open to it I'll create a pull request with the changes after making sure the tests all still pass.

**Comment by christianalfoni** [comment]
Hi @marnusw ,

Thanks for taking the time to review the implementation :-)

The reason I implemented `setInputValidationErrors` is because that one will always go through all inputs and set the valid state based on any errors passed. It basically resets the input if there was an error there, and then there is no error. So it is needed.

The `updateInputsWithError` does the opposite. It goes through any errors passed and set those errors, as you say.

That said, you might be right :-) But I believe the first method has to be used, because it makes sure that any inputs that current state is error is reset to valid state when there is no error anymore. Does that make sense?

I agree that `getCurrentValues()` eliminates `updateModel()`. Cleans up the code :-)

Would be great if created a pull request for this, though make sure that passing errors on the form, and then removing them, resets the inputs to valid state.

**Comment by marnusw** [comment]
Sure thing, I'll work on the PR in the very near future. Thanks.

**Comment by christianalfoni** [comment]
Cool! I will just close this issue. Please comment again if you want to discuss some details on this :)
