### ISSUE TITLE
getErrorMessage not returning server error

### ISSUE THREAD

**Issue by frost555** [christianalfoni/formsy-react#88]
The code that sets the error is 

    updateInputsWithError: function (errors) {
      Object.keys(errors).forEach(function (name, index) {
        var component = this.inputs[name];

        if (!component) {
          throw new Error('You are trying to update an input that does not exists. Verify errors object with input names. ' + JSON.stringify(errors));
        }

        var args = [{
          _isValid: false,
          _serverError: errors[name]
        }];
        component.setState.apply(component, args);
      }.bind(this));
    },

The code that reads the error is 

    getErrorMessage: function () {
      return !this.isValid() || this.showRequired() ? this.state._validationError : null;
    },

As you can see, _serverError is not read.

**Comment by frost555** [comment]
ASP.NET Web API server by default returns errors in the following format:

     {"modelState":{"email":["Email is already in use"]}}

There is an array associated with property name. Would it be possible to support such responses? At  least with array size equal to  one.

**Comment by christianalfoni** [comment]
Hi @frost555 , since version 0.11 Formsy no longer handles Ajax directly. You have to wire it up manually. The reason is that Formsy should focus on being a good form validation tool, not ajax tool :-)

So by using `onSubmit` or `onValidSubmit` you can do the ajax call there and reset/invalidate the form with the callbacks received as arguments to these methods. That way you can also map whatever response you get from the server.

I have fixed the error you pointed out, thanks for that ;-)
